version: "1.2.2"
locale: EN
notifications: true
gui:
  animation: true
  next-page:
    slot: 53
    item: ENDER_PEARL
  previous-page:
    slot: 45
    item: ENDER_EYE
  close:
    slot: 49
    item: BARRIER
  reset:
    slot: 50
    item: RED_STAINED_GLASS_PANE
  borders: BLACK_STAINED_GLASS_PANE
  default-icon: LEATHER_BOOTS
permissions:
  # General
  menu: "trelytra.menu"
  admin: "trelytra.admin"
  changelog: "trelytra.changelog"
  debug: "trelytra.debug"
  # Effects
  rainbow: "trelytra.rainbow"
  tail: "trelytra.tail"
  sonic: "trelytra.sonic"