# Do not change!
version: "1.3.0"
# Messages locale
locale: EN
# Toggle timings report for effects
timings: true
# Toggle notifications
# Players can disable notifications for themselves even if notifications is enabled
# If you disable notifications, it will be disabled for all players
notifications: true
# GUI options
gui:
  animation: true # GUI animations
  next-page: # Next page button item
    slot: 53
    item:
      material: ENDER_PEARL
  previous-page: # Previous page button item
    slot: 45
    item:
      material: ENDER_EYE
  close: # Close button item
    slot: 49
    item:
      material: BARRIER
  reset: # Reset effects button item
    slot: 50
    item:
      material: RED_STAINED_GLASS_PANE
  borders: # Borders item
    material: BLACK_STAINED_GLASS_PANE
  default-icon: # Default effects icon item
    material: LEATHER_BOOTS
permissions:
  # General
  menu: "trelytra.menu" # Base command permission
  admin: "trelytra.admin" # Admin commands permission
  changelog: "trelytra.changelog" # Changelog command permission
  notification: "trelytra.notification" # Notification (and notification command) permission
  debug: "trelytra.debug" # Debug command permission
  # Effects Visibility
  # You can show TrElytra effects for the players who have permission, just set the "effects_visibility_permission" to true
  # If this enabled, give the "can_see_effects" permission to players
  effects_visibility_permission: false
  can_see_effects: "trelytra.can_see_effects" #
  # Only some effects have permission by default.
  # Please check the effects.yml file if you want to add permissions to effects.
  # You can read the wiki page for detailed information: https://github.com/Treasure-Inc/Treasure-Elytra/wiki/Permissions
  rainbow: "trelytra.rainbow" # Permission for rainbow effects group
  tail: "trelytra.tail" # Permission for tail effects group
  sonic: "trelytra.sonic" # Permission for sonic effect